-- Electricity Bill Management — PostgreSQL schema
-- Create the database, load this file, then seed sample data:
--   createdb electricity
--   psql -d electricity -f server/database/schema.sql
--   cd server && npm run seed

-- ---------------------------------------------------------------------------
-- Auth
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_login (
  c_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR(100) NOT NULL UNIQUE,
  password  VARCHAR(255) NOT NULL            -- bcrypt hash
);

CREATE TABLE IF NOT EXISTS admin_login (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR(100) NOT NULL UNIQUE,
  password  VARCHAR(255) NOT NULL            -- bcrypt hash
);

-- ---------------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS customer_details (
  c_id      INT PRIMARY KEY REFERENCES user_login (c_id) ON DELETE CASCADE,
  name      VARCHAR(100) NOT NULL,
  email     VARCHAR(150),
  address   VARCHAR(255)
);

-- ---------------------------------------------------------------------------
-- Bills
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bills (
  bill_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_id      INT NOT NULL REFERENCES user_login (c_id) ON DELETE CASCADE,
  amt_topay NUMERIC(10, 2) NOT NULL,
  due_date  DATE,
  status    TEXT DEFAULT 'unpaid' CHECK (status IN ('paid', 'unpaid'))
);

CREATE TABLE IF NOT EXISTS bills_paid (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_id           INT NOT NULL,
  name           VARCHAR(100),
  bill_amt       NUMERIC(10, 2) NOT NULL,
  method         VARCHAR(50) DEFAULT 'Card',
  bill_paid_date TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Messaging
-- ---------------------------------------------------------------------------

-- Customer -> admin (complaints and queries)
CREATE TABLE IF NOT EXISTS inbox_admin (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_id      INT NOT NULL,
  name      VARCHAR(100),
  email     VARCHAR(150),
  subject   VARCHAR(200),
  message   TEXT NOT NULL,
  status    TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  replied   BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMPTZ DEFAULT now()
);

-- Admin -> customer (replies and notices)
CREATE TABLE IF NOT EXISTS inbox_user (
  id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_id      INT NOT NULL REFERENCES user_login (c_id) ON DELETE CASCADE,
  subject   VARCHAR(200),
  message   TEXT NOT NULL,
  is_read   BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMPTZ DEFAULT now()
);
